import type { TabularTable } from '../tabular/columns.js'
import { normalizeColumns } from '../tabular/columns.js'

export interface SqlInsertsOptions {
  /** The name the table gets. Cleaned before it reaches the SQL. */
  tableName: string
}

/**
 * Rows per INSERT.
 *
 * One statement per row is unreadable and slow to replay; one statement for a
 * hundred thousand rows overruns `max_allowed_packet` on MySQL and the
 * statement-length limits elsewhere. Batching keeps the file replayable
 * everywhere without making it a single unbreakable line.
 */
const ROWS_PER_INSERT = 500

/** Control characters have no place in an identifier or in a file. */
const CONTROL = /[\x00-\x1F\x7F]/g

/**
 * A double-quoted identifier, which is what standard SQL uses.
 *
 * Doubling an embedded quote is the standard escape, so a sheet named `user"s`
 * cannot close the identifier early and turn the rest of the line into syntax.
 */
function identifier(name: string): string {
  return '"' + name.replace(/"/g, '""') + '"'
}

/**
 * A single-quoted string literal.
 *
 * Doubling the embedded quote is the only escape standard SQL defines, and it
 * is the only one used here - no backslash sequences, which is what lets the
 * same file mean the same thing in every engine (see the header this writer
 * emits). A value carrying `'); DROP TABLE t; --` therefore survives as text.
 */
function literal(value: string): string {
  return "'" + value.replace(/'/g, "''") + "'"
}

/**
 * An empty cell becomes NULL rather than an empty string.
 *
 * A spreadsheet does not distinguish the two - a blank cell and a cell holding
 * "" look the same and read the same - so the one that survives a round trip
 * through more engines is the better answer.
 */
function value(cell: string | null): string {
  return cell === null || cell === '' ? 'NULL' : literal(cell)
}

/** A table name a database will accept, taken from a sheet name it will not. */
function tableIdentifier(name: string): string {
  const cleaned = name.replace(CONTROL, '').replace(/\s+/g, ' ').trim()
  return cleaned.length > 0 ? cleaned : 'sheet'
}

/**
 * Write a table as a SQL script: one CREATE TABLE and batched INSERTs.
 *
 * Every column is declared TEXT. A spreadsheet has no schema - a column of
 * digits may be a quantity, an order number or a phone number, and guessing
 * wrong silently drops a leading zero or rounds an identifier. TEXT keeps
 * exactly what was in the cell and leaves the typing to whoever loads it, who
 * knows what the data is.
 *
 * The script opens with a MySQL-only mode line. MySQL and MariaDB depart from
 * the standard in two ways that matter here: they read `"` as a string
 * delimiter rather than as an identifier quote, and they treat a backslash as
 * an escape inside a string. The second is the dangerous one - a cell ending
 * in a backslash would escape the closing quote and let the next value be read
 * as SQL. `ANSI_QUOTES` and `NO_BACKSLASH_ESCAPES` turn both off, so this file
 * is plain standard SQL in MySQL too. It is wrapped in a versioned comment, so
 * every other engine reads it as a comment and ignores it.
 */
export function toSqlInserts(
  table: TabularTable,
  { tableName }: SqlInsertsOptions,
): string {
  const name = tableIdentifier(tableName)
  const width = table.rows.reduce(
    (widest, row) => Math.max(widest, row.length),
    table.columns.length,
  )
  const columns = normalizeColumns(table.columns, width)

  const lines: string[] = [
    `-- ${name}`,
    '-- Generated by Converter Hub. Every column is TEXT: a spreadsheet carries',
    "/*!40101 SET SESSION sql_mode = 'ANSI_QUOTES,NO_BACKSLASH_ESCAPES' */;",
    '',
    `CREATE TABLE ${identifier(name)} (`,
    columns.map((column) => `  ${identifier(column)} TEXT`).join(',\n'),
    ');',
    '',
  ]

  const columnList = columns.map(identifier).join(', ')

  for (let start = 0; start < table.rows.length; start += ROWS_PER_INSERT) {
    const batch = table.rows.slice(start, start + ROWS_PER_INSERT)

    lines.push(`INSERT INTO ${identifier(name)} (${columnList})`, 'VALUES')
    lines.push(
      batch
        .map((row, index) => {
          // Rows can be shorter than the header; the missing cells are absent,
          // not empty, and NULL is what absent means here.
          const cells = columns.map((_, column) => value(row[column] ?? null))
          const end = index === batch.length - 1 ? ';' : ','
          return `  (${cells.join(', ')})${end}`
        })
        .join('\n'),
    )
    lines.push('')
  }

  return lines.join('\n')
}
