import type { TabularTable } from '../tabular/columns.js'
import { normalizeColumns } from '../tabular/columns.js'

export interface SqlInsertsOptions {
  tableName: string
}

const ROWS_PER_INSERT = 500

const CONTROL = /[\x00-\x1F\x7F]/g

function identifier(name: string): string {
  return '"' + name.replace(/"/g, '""') + '"'
}

function literal(value: string): string {
  return "'" + value.replace(/'/g, "''") + "'"
}

function value(cell: string | null): string {
  return cell === null || cell === '' ? 'NULL' : literal(cell)
}

function tableIdentifier(name: string): string {
  const cleaned = name.replace(CONTROL, '').replace(/\s+/g, ' ').trim()
  return cleaned.length > 0 ? cleaned : 'sheet'
}

export function toSqlInserts(
  table: TabularTable,
  { tableName }: SqlInsertsOptions,
): string {
  const name = tableIdentifier(tableName)
  const width = table.rows.reduce(
    (widest, row) => Math.max(widest, row.length),
    table.columns.length,
  )
  const columns = normalizeColumns(table.columns, width)

  const lines: string[] = [
    `-- ${name}`,
    '-- Generated by Converter Hub. Every column is TEXT: a spreadsheet carries',
    "/*!40101 SET SESSION sql_mode = 'ANSI_QUOTES,NO_BACKSLASH_ESCAPES' */;",
    '',
    `CREATE TABLE ${identifier(name)} (`,
    columns.map((column) => `  ${identifier(column)} TEXT`).join(',\n'),
    ');',
    '',
  ]

  const columnList = columns.map(identifier).join(', ')

  for (let start = 0; start < table.rows.length; start += ROWS_PER_INSERT) {
    const batch = table.rows.slice(start, start + ROWS_PER_INSERT)

    lines.push(`INSERT INTO ${identifier(name)} (${columnList})`, 'VALUES')
    lines.push(
      batch
        .map((row, index) => {
          const cells = columns.map((_, column) => value(row[column] ?? null))
          const end = index === batch.length - 1 ? ';' : ','
          return `  (${cells.join(', ')})${end}`
        })
        .join('\n'),
    )
    lines.push('')
  }

  return lines.join('\n')
}
